version: '3.9'

services:
  # Mongodb
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # API
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db

volumes:
  mongo_db:
    driver: local